### ISSUE TITLE
[Enhancement] Manual Trigger

### ISSUE THREAD

**Issue by theonetrueduddy** [Elemental-Re/crossblade#1]
Hey there! Love the module, and always wanted to see something like this.

Would it be possible to add a way to manually trigger a change between layers? I'd love to be able to use this to have adaptive music in non-combat scenes too :) Perhaps allowing for such by macro?

Either way, good work!

**Comment by Elemental-Re** [comment]
Thank you for the kind words!

Expanding support for non combat events and manual triggers is planned for a future release. I don't have a timeline for it right now, but it's something I want to see too so stay tuned.

**Comment by Elemental-Re** [comment]
There's a [new release](https://github.com/Elemental-Re/crossblade/releases/tag/1.1.0) that feature manual triggers (called Custom Events) that's I'm going to officially push to the Foundry client later tonight or tomorrow, but you can try installing using the following manifest link if you want to try it out before then. Let me know if this is what you were looking for.

https://github.com/Elemental-Re/crossblade/releases/download/1.1.0/module.json

**Comment by Elemental-Re** [comment]
Completed as of 1.1.0
