### ISSUE TITLE
Configuration window errors out if a sound is already present

### ISSUE THREAD

**Issue by Hertzila** [Elemental-Re/crossblade#5]
Hello. If I try to edit a playlist sound that already has sounds within it, the window fails to load and errors out, making it impossible to edit the layers.  

It seems like the module is using a "getProperty" Handlebars helper from somewhere in something, and it fails to load if that thing is not present.  

Error log linked.  

[localhost-log.log](https://github.com/Elemental-Re/crossblade/files/9005742/localhost-log.log)

**Comment by Elemental-Re** [comment]
Thank you for the report. I think I have a sense of the cause and how to fix it, but for completeness's sake can I ask what version of foundry and the system you are using are both on for your world?

**Comment by Hertzila** [comment]
Sure.  
Foundry is V9, build 269.  
System is StargateRPG, specifically my fork of it here: https://github.com/Hertzila/StargateRPGSystem  

I can try and see what happens if I try another system that is less monkey-patched.

**Comment by Elemental-Re** [comment]
Yeah, I suspect maybe that helper comes from the 5e system. That was my mistake. I think I can replace it pretty quickly. Thanks again.

**Comment by Elemental-Re** [comment]
I just pushed a [new release](https://github.com/Elemental-Re/crossblade/releases/tag/1.0.7) that should resolve this. Let me know if you're still having issues after updating.
